ServerEvents.recipes(event => {
    event.replaceInput({ input:'immersiveengineering:slab_sheetmetal_copper'},'immersiveengineering:slab_sheetmetal_copper','createdeco:copper_sheet_slab')
    event.replaceInput({ input:'immersiveengineering:sheetmetal_copper'},'immersiveengineering:sheetmetal_copper','createdeco:copper_sheet_metal')
    event.replaceInput({ input:'immersiveengineering:plate_copper'},'immersiveengineering:plate_copper','create:copper_sheet')
    event.replaceInput({ input:'iceandfire:copper_nugget'},'iceandfire:copper_nugget','create:copper_nugget')
    event.replaceInput({ input:'createdeco:iron_sheet_slab'},'createdeco:iron_sheet_slab','immersiveengineering:slab_sheetmetal_iron')
    event.replaceInput({ id:'immersiveengineering:crafting/toolupgrade_revolver_bayonet'}, 'immersiveengineering:sword_steel','mekanismtools:steel_sword')
    event.replaceInput({ input: 'immersiveengineering:dust_steel'}, 'immersiveengineering:dust_steel', 'mekanism:dust_steel')
    event.replaceInput({ input:'createdeco:gold_coin'}, 'createdeco:gold_coin', 'thermal:gold_coin')
    event.replaceInput({ input:'createdeco:copper_coin'}, 'createdeco:copper_coin', 'thermal:copper_coin')
    event.replaceInput({ input:'immersiveengineering:dust_constantan'}, 'immersiveengineering:dust_constantan', 'thermal:constantan_dust')
    event.replaceInput([{input:'thermal:gold_plate'}, {input: "immersiveengineering:plate_gold"}], ['thermal:gold_plate', 'immersiveengineering:plate_gold'], 'create:golden_sheet')
    event.replaceInput([{input: 'immersiveengineering:ingot_steel'}, {input: 'ad_astra:steel_ingot'}],['immersiveengineering:ingot_steel', 'ad_astra:steel_ingot'],'mekanism:ingot_steel')
})