ServerEvents.recipes(event => {
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'minecraft:glowstone' })
    event.remove({ id: 'create_sa:copper_hoe_recipe' })
    event.remove({ id: 'create_sa:copper_shovel_recipe' })
    event.remove({ id: 'create_sa:copper_pickaxe_recipe' })
    event.remove({ id: 'create_sa:copper_axe_recipe' })
    event.remove({ id: 'create_sa:copper_sword_recipe' })
    event.remove({ id: 'create_sa:copper_helmet_recipe' })
    event.remove({ id: 'create_sa:copper_leggings_recipe' })
    event.remove({ id: 'create_sa:copper_chestplate_recipe' })
    event.remove({ id: 'create_sa:copper_boots_recipe' })
    event.remove({ id: 'create_sa:copper_hoe_recipe' })
    event.remove({ id: 'create_sa:copper_hoe_recipe' })
    event.remove({ id: 'create_sa:copper_flamethrower_recipe' })
    //↓,removes copper nuggets to ingot recipes from immersive, thermal, and ice&fire
    event.remove({id: 'immersiveengineering:crafting/nugget_copper_to_copper_ingot'})    
    event.remove({id: 'thermal:storage/copper_ingot_from_nuggets'})
    event.remove({id: 'create:blasting/nickel_ingot_compat_thermal'})
    event.remove({id: 'create:smelting/nickel_ingot_compat_thermal'})
    event.remove({id: 'create:blasting/ingot_nickel_compat_immersiveengineering'})
    event.remove({id: 'create:splashing/thermal/crushed_raw_nickel'})
    event.remove({id: 'create:smelting/nickel_ingot_compat_thermal'})
    event.remove({id: 'thermal:furnace_1499172612'})
})