JEIEvents.hideItems(event => {

    event.hide([
        /ae2:facade/,// ← ae2's facades
        //creative stuff ↓
        ['arseng:creative_source_cell',
        'theoneprobe:creativeprobe',
        'ars_nouveau:creative_source_jar', 
        'ars_nouveau:creative_spell_book',
        'securitycraft:admin_tool', 
        'apotheosis:boss_summoner', 
        'ae2:creative_energy_cell', 
        'ae2:creative_item_cell', 
        'ae2:creative_fluid_cell', 
        'appmek:creative_chemical_cell', 
        'botania:creative_pool', 
        'botania:infrangible_platform', 
        'botania:lens_storm',
        'botania:corporea_spark_creative', 
        'buildinggadgets:construction_paste_container_creative', 
        'create:creative_motor', 'create:creative_fluid_tank', 
        'create:creative_crate', 'create:creative_blaze_cake', 
        'create:handheld_worldshaper', 
        'createaddition:creative_energy', 
        'create_sa:creative_filling_tank', 
        'iceandfire:creative_dragon_meal', 
        'mekanism:creative_bin', 
        'mekanism:creative_fluid_tank', 
        'mekanism:creative_energy_cube', 
        'mekanism:creative_chemical_tank',
        'thermal:rf_coil_creative_augment', 
        'thermal:fluid_tank_creative_augment', 
        'thermal:machine_efficiency_creative_augment', 
        'thermal:machine_catalyst_creative_augment', 
        'immersiveengineering:capacitor_creative', 
        Item.of('botania:mana_tablet', '{creative:1b,mana:500000}'),
        //coppers ↓
        'create_sa:copper_hoe',
        "create_sa:copper_sword",
        'create_sa:copper_shovel',
        'create_sa:copper_axe',
        'create_sa:copper_pickaxe',
        'create_sa:copper_helmet',
        'create_sa:copper_leggings',
        'create_sa:copper_chestplate',
        'create_sa:copper_boots',
        'create_sa:flamethrower',
        'iceandfire:copper_nugget',
        'thermal:copper_nugget',
        'immersiveengineering:nugget_copper',
        'immersiveengineering:slab_sheetmetal_copper',
        'immersiveengineering:sheetmetal_copper',
        'immersiveengineering:slab_sheetmetal_copper',
        'immersiveengineering:sheetmetal_copper',
        'immersiveengineering:plate_copper', 
        'thermal:copper_plate',
        'mekanism:dust_copper',
        'immersiveengineering:dust_copper',
        //nickels ↓
        'immersiveengineering:ingot_nickel', 
        'immersiveengineering:nugget_nickel', 
        'immersiveengineering:raw_nickel', 
        'immersiveengineering:plate_nickel', 
        'immersiveengineering:dust_nickel', 
        'immersiveengineering:ore_nickel', 
        'immersiveengineering:deepslate_ore_nickel', 
        'immersiveengineering:storage_nickel', 
        'immersiveengineering:slab_storage_nickel',
        'immersiveengineering:raw_block_nickel',
        'createaddition:diamond_grit', 
        'mekanism:dust_diamond',
        'ad_astra:steel_ingot', 
        'immersiveengineering:ingot_steel',
        'immersiveengineering:hoe_steel', 
        'immersiveengineering:axe_steel', 
        'immersiveengineering:shovel_steel', 
        'immersiveengineering:pickaxe_steel', 
        'immersiveengineering:sword_steel',
        'immersiveengineering:dust_steel', 
        'immersiveengineering:plate_steel', 
        'immersiveengineering:nugget_steel', 
        'ad_astra:steel_nugget', 
        'ad_astra:steel_block', 
        'mekanism:block_steel', 
        'immersiveengineering:armor_steel_feet', 
        'immersiveengineering:armor_steel_legs', 
        'immersiveengineering:armor_steel_chest', 
        'immersiveengineering:armor_steel_head',
        'immersiveengineering:wire_copper',
        'thermal:gold_plate', 
        'immersiveengineering:plate_gold',
        'mekanism:dust_netherite',
        'thermal:copper_coin',
        'thermal:gold_coin'
        ]
    ])    
})

